### PR TITLE
auctex: import from homebrew/tex.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
That tap is being killed and this was the most popular formula.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@dunn Want a global TeX installation here?

**Comment by dunn** [comment]
@MikeMcQuaid does Travis need one? The tests are passing?

**Comment by MikeMcQuaid** [comment]
@dunn It's skipping the actual installation but running e.g. `brew audit` as MacTex isn't installed. Up to you if you want the overhead of `brew cask install mactex` on every build.

**Comment by dunn** [comment]
BasicTeX is just a few hundred MB, right?

**Comment by dunn** [comment]
But of course `brew cask install basictex` won't work on the Linux build.  Merging for now, I'll think about how to actually test the install. Thanks!

**Comment by rwhogg** [comment]
> But of course brew cask install basictex won't work on the Linux build.

The recommended way to install TeX on Linuxbrew is the `texlive` formula. It's not available upstream, though.

**Comment by dunn** [comment]
We can use Cask on the macOS builds; but that's a 2GB formula we'd have to install for each Linux run, right?

**Comment by rwhogg** [comment]
> We can use Cask on the macOS builds;

Yeah, wasn't advising against that, just meant that it specifically has to be *Linuxbrew*, not just Brew-running-on-Linux. My apologies for the confusion.

> but that's a 2GB formula we'd have to install for each Linux run, right?

The bottle (as of this writing) is 255 MB and after installation it's around 467 MB. Could be worse, I suppose, but it's definitely pretty large.

**Comment by dunn** [comment]
> Well, that's smaller than I thought.  I think Travis can be configured to cache certain things/directories, so we might be able to get away with just downloading it once per day or whatever.

**Pull request closed without merging**
