### PR TITLE
Add some more formulae, plus a neat little `generate_autoloads` helper method

### PR DESCRIPTION
**Pull request by MerelyAPseudonym**

### CODE REVIEW

**Comment by dunn** [comment]
Oh, cool!

One test failure was an API rate-limit issue. Otherwise just one audit catch:
```
==> audit problems
homebrew/emacs/diminish:
 * Description is too long. "name: desc" should be less than 80 characters.
Length is calculated as homebrew/emacs/diminish + desc. (currently 82)
```

**Comment by dunn** [comment]
Is there any downside to automatically running `generate_autoloads` for every formula? We might be able to patch the install method.

**Comment by dunn** [comment]
Sorry for the delays! Cherry-picked Projectile and Diminish, thank you!

Regarding use-package and bind-key, should they be one formula, since they're part of the same repository? I see MELPA separates them but that doesn't mean we have to.

And the autoloads generator is going to need to be tweaked a bit, since the directory in `site-lisp` doesn't have to match the package name (see the recently renamed `dash-emacs`).

**Comment by bfontaine** [comment]
@dunn `projectile` uses `generate_autoloads` so the formula doesn’t install anymore:
```
==> Installing projectile from homebrew/homebrew-emacs
==> Cloning https://github.com/bbatsov/projectile.git
Cloning into '/Library/Caches/Homebrew/projectile--git'...
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 29 (delta 0), reused 15 (delta 0), pack-reused 0
Unpacking objects: 100% (29/29), done.
Checking connectivity... done.
==> Checking out branch master
==> Byte compiling projectile.el
Wrote /private/tmp/projectile20151027-12262-ziwhuh/projectile.elc
Error: undefined local variable or method `generate_autoloads' for #<Formulary::FormulaNamespace7bd6b45b3e910c65ae313e2ca70be2c1::Projectile:0x007f827aa07838>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-emacs/Formula/projectile.rb:19:in `install'
/usr/local/Library/Homebrew/build.rb:129:in `block in install'
/usr/local/Library/Homebrew/formula.rb:886:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1454:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1446:in `stage'
/usr/local/Library/Homebrew/formula.rb:882:in `brew'
/usr/local/Library/Homebrew/build.rb:107:in `install'
/usr/local/Library/Homebrew/build.rb:176:in `<main>'
```

**Comment by dunn** [comment]
Ahaha of course. Thanks for catching that!

**Comment by bfontaine** [comment]
…And `diminish` too :wink:

**Comment by dunn** [comment]
:crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face:

**Comment by dunn** [comment]
I'm still open to merging the `generate_autoloads` method if you feel like picking this up again.

**Comment by MerelyAPseudonym** [comment]
@dunn Sorry I never followed up months ago. This dropped off my radar, but if I get time over the next few days I'll see if I can pick this up again!

**Comment by markhallm** [comment]
@MerelyAPseudonym It would be great to get the autoload generation into Homebrew Emacs. I can see that the changes in this pull request generate the autoloads files. However, what mechanism in Emacs will then load the autoloads files for each package? Is there something built into Emacs that will do this for any autoload files found on the load path? Or what code needs to be added to the Emacs initialization to ensure the autoload files are loaded?

**Comment by markhallm** [comment]
@MerelyAPseudonym Related to my question above, it seems like Linux distributions such as Fedora and Debian solve it by providing a `/usr/share/emacs/site-lisp/site-start.d` directory which is loaded by default at Emacs startup. Then the autoload files of packages are simply put in that directory. This shows how Fedora does it: https://src.fedoraproject.org/rpms/emacs/blob/master/f/site-start.el

**Pull request closed without merging**
